{
  imports = [
    ./bufferline.nix
    ./cmp.nix
    ./comment.nix
    ./ftplugins.nix
    ./gitsigns.nix
    ./keymaps.nix
    ./lsp.nix
    ./lualine.nix
    ./markview.nix
    ./none-ls.nix
    ./nvim-tree.nix
    ./options.nix
    ./schemastore.nix
    ./telescope.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./utils
  ];
}
