{
  imports = [
    ./autopairs.nix
    ./bufferline.nix
    ./comment.nix
    ./keymaps.nix
    ./lsp.nix
    ./lualine.nix
    ./markview.nix
    ./neo-tree.nix
    ./none-ls.nix
    ./options.nix
    ./telescope.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./undotree.nix
    ./which-key.nix
  ];
}
